networks:
  testing_network:
    driver: bridge
services:
  dfmailbox:
    init: true
    build:
      context: ./server
      target: dev
      args:
        TESTING: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s
      start_interval: 0.5s
    ports:
      - 8080
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      PORT: 8080
      DATABASE_URL: postgres://dfuser:testing_postgres_password@postgres:5432/dfmailbox
      TESTING_MODE: true
      HOST: ${DFMC_ADDRESS}
      SECRET_KEY: ${DFMC_PRIVATE_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./server/src
    stop_grace_period: 1s
    restart: no
    networks:
      - testing_network
    extra_hosts:
      # For some reason, host gateway doesn't work resulting in this terribleness
      - "host.docker.internal:${DFMC_HOST_GATEWAY:-host-gateway}"

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations/"
      - "-database=postgres://dfuser:testing_postgres_password@postgres:5432/dfmailbox?sslmode=disable"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: no
    networks:
      - testing_network

  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: dfmailbox
      POSTGRES_USER: dfuser
      POSTGRES_PASSWORD: testing_postgres_password
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dfuser -d dfmailbox"]
      interval: 3s
      timeout: 5s
      start_period: 5s
      start_interval: 0.5s
      retries: 5
    networks:
      - testing_network
    tmpfs:
      - /var/lib/postgresql/data:size=100m
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_wal_size=4GB -c checkpoint_timeout=30min -c wal_buffers=16MB

